import { UserConfig, Translation } from './types';

export const DEFAULT_USER_CONFIG: UserConfig = {
  showTemperatureChart: true,
  showPressureChart: true,
  showPowerChart: false,
  allowSetpointControl: true,
  allowPowerControl: false,
  alarmSoundEnabled: true,
};

export const TRANSLATIONS: Record<'en' | 'fr', Translation> = {
  en: {
    // Navigation & Sessions
    dashboard: 'Dashboard',
    controls: 'Controls',
    settings: 'Settings',
    users: 'User Management',
    logout: 'Logout',
    about: 'About',
    terms: 'Terms of Service',
    privacy: 'Privacy Policy',
    welcome: 'Welcome back',

    // Login Page
    clientPortal: 'Client Portal',
    industrialMonitoring: 'Secure access to your industrial monitoring dashboard.',
    companyId: 'Company ID',
    password: 'Secure Password',
    rememberDevice: 'Remember device',
    forgotAccess: 'Forgot Access?',
    accessDashboard: 'Access Dashboard',
    visitWebsite: 'Visit Official Website',
    systemOperational: 'System Operational',
    tagline: 'The specialist in industrial and commercial cooling. We support you from study to completion.',

    // Dashboard & Controls
    systemStatus: 'System Status',
    temperature: 'Temperature',
    pressure: 'Pressure',
    setpoint: 'Setpoint',
    active: 'Active',
    inactive: 'Inactive',
    save: 'Save Changes',
    cancel: 'Cancel',
    alarms: 'Alarms',
    acknowledge: 'Acknowledge',
    clearAll: 'Clear All',
    noActiveAlarms: 'No active alarms',
    viewHistory: 'View History',

    // Settings
    preferences: 'Preferences and security',
    language: 'Language',
    selectLanguage: 'Select your preferred interface language.',
    security: 'Security',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    updatePassword: 'Update Password',
    forgotAccessTitle: 'Forgot Access?',
    forgotAccessDescription: 'For security reasons, access recovery is managed by your system administrator. Please contact our technical support team to reset your credentials.',
    contactSupport: 'Contact Support',
    close: 'Close',
    passwordChangedSuccess: 'Password updated successfully!',
    passwordChangeError: 'Error updating password. Please try again.',
    confirmPassword: 'Confirm New Password',

    // Corporate Pages
    aboutPlatform: 'About Platform',
    productInfo: 'Product Information',
    appName: 'Application Name',
    appDescription: 'Short Description',
    appDescriptionText: 'Industrial IoT Platform for Real-time Monitoring & Remote Control of Refrigeration Systems.',
    versionBuild: 'Version / Build',
    releaseDate: 'Release Date',
    techSpecs: 'Technical Specifications',
    specMqtt: 'MQTT Protocol',
    specSecurity: 'Security',
    specCapacity: 'Capacity',
    specArchitecture: 'Architecture',
    specDatabase: 'Database',
    specHosting: 'Hosting',
    companyInfo: 'Company Information',
    addressInfo: 'Afric Froid HQ',
    allRightsReserved: '© 2026 Afric Froid. All rights reserved.',
    devCredits: 'Development Credits',
    architectureLead: 'Architecture & Lead Development',
    inPartnershipWith: 'In Partnership With',
    poweredBy: 'Powered By',
    alarmSound: 'Alarm Sound',
    enableAlarmSound: 'Audio alert enabled',
    disableAlarmSound: 'Audio alert disabled',
    testSound: 'Test Sound'
  },
  fr: {
    // Navigation & Sessions
    dashboard: 'Tableau de bord',
    controls: 'Commandes',
    settings: 'Paramètres',
    users: 'Gestion des utilisateurs',
    logout: 'Déconnexion',
    about: 'À propos',
    terms: 'Conditions d\'utilisation',
    privacy: 'Politique de confidentialité',
    welcome: 'Bon retour',

    // Login Page
    clientPortal: 'Portail Client',
    industrialMonitoring: 'Accès sécurisé à votre tableau de bord de surveillance industrielle.',
    companyId: 'ID Entreprise',
    password: 'Mot de passe sécurisé',
    rememberDevice: 'Se souvenir de l\'appareil',
    forgotAccess: 'Accès oublié ?',
    accessDashboard: 'Accéder au tableau de bord',
    visitWebsite: 'Visiter le site officiel',
    systemOperational: 'Système Opérationnel',
    tagline: 'Le spécialiste du froid industriel et commercial. Nous vous accompagnons de l\'étude à la réalisation.',

    // Dashboard & Controls
    systemStatus: 'État du système',
    temperature: 'Température',
    pressure: 'Pression',
    setpoint: 'Consigne',
    active: 'Actif',
    inactive: 'Inactif',
    save: 'Enregistrer',
    cancel: 'Annuler',
    alarms: 'Alarmes',
    acknowledge: 'Acquitter',
    clearAll: 'Tout effacer',
    noActiveAlarms: 'Aucune alarme active',
    viewHistory: 'Voir l\'historique',

    // Settings
    preferences: 'Préférences et sécurité',
    language: 'Langue',
    selectLanguage: 'Sélectionnez votre langue d\'interface préférée.',
    security: 'Sécurité',
    currentPassword: 'Mot de passe actuel',
    newPassword: 'Nouveau mot de passe',
    updatePassword: 'Modifier le mot de passe',
    forgotAccessTitle: 'Accès Oublié ?',
    forgotAccessDescription: 'Pour des raisons de sécurité, la récupération d\'accès est gérée par votre administrateur système. Veuillez contacter notre équipe de support technique pour réinitialiser vos identifiants.',
    contactSupport: 'Contacter le Support',
    close: 'Fermer',
    passwordChangedSuccess: 'Mot de passe mis à jour avec succès !',
    passwordChangeError: 'Erreur lors de la mise à jour du mot de passe. Veuillez réessayer.',
    confirmPassword: 'Confirmer le nouveau mot de passe',

    // Corporate Pages
    aboutPlatform: 'À propos de la plateforme',
    productInfo: 'Informations sur le produit',
    appName: 'Nom de l\'application',
    appDescription: 'Brève description',
    appDescriptionText: 'Plateforme IoT industrielle pour la surveillance en temps réel et le contrôle à distance des systèmes de réfrigération.',
    versionBuild: 'Version / Build',
    releaseDate: 'Date de sortie',
    techSpecs: 'Spécifications Techniques',
    specMqtt: 'Protocole MQTT',
    specSecurity: 'Sécurité',
    specCapacity: 'Capacité',
    specArchitecture: 'Architecture',
    specDatabase: 'Base de données',
    specHosting: 'Hébergement',
    companyInfo: 'Informations sur l\'entreprise',
    addressInfo: 'Siège Afric Froid',
    allRightsReserved: '© 2026 Afric Froid. Tous droits réservés.',
    devCredits: 'Crédits de Développement',
    architectureLead: 'Architecture et Développement Principal',
    inPartnershipWith: 'En Partenariat Avec',
    poweredBy: 'Propulsé Par',
    alarmSound: 'Alarmes Sonores',
    enableAlarmSound: 'Alerte sonore activée',
    disableAlarmSound: 'Alerte sonore désactivée',
    testSound: 'Tester le son'
  }
};
