import { UserConfig, Translation } from './types';

/** Must match scheduled `prune_telemetry_readings` policy (days of history kept in DB). */
export const TELEMETRY_RETENTION_DAYS = 7;

export const DEFAULT_USER_CONFIG: UserConfig = {
  showTemperatureChart: true,
  showPressureChart: true,
  showPowerChart: false,
  allowSetpointControl: true,
  allowPowerControl: false,
  alarmSoundEnabled: true,
};

export const TRANSLATIONS: Record<'en' | 'fr', Translation> = {
  en: {
    // Navigation & Sessions
    dashboard: 'Dashboard',
    controls: 'Controls',
    settings: 'Settings',
    users: 'User Management',
    logout: 'Logout',
    about: 'About',
    terms: 'Terms of Service',
    privacy: 'Privacy Policy',
    welcome: 'Welcome back',

    // Login Page
    clientPortal: 'Client Portal',
    industrialMonitoring: 'Secure access to your industrial monitoring dashboard.',
    companyId: 'Company ID',
    password: 'Secure Password',
    rememberDevice: 'Remember device',
    forgotAccess: 'Forgot Access?',
    accessDashboard: 'Access Dashboard',
    visitWebsite: 'Visit Official Website',
    systemOperational: 'System Operational',
    tagline: 'The specialist in industrial and commercial cooling. We support you from study to completion.',

    // Dashboard & Controls
    systemStatus: 'System Status',
    temperature: 'Temperature',
    pressure: 'Pressure',
    setpoint: 'Setpoint',
    active: 'Active',
    inactive: 'Inactive',
    save: 'Save Changes',
    cancel: 'Cancel',
    alarms: 'Alarms',
    acknowledge: 'Acknowledge',
    clearAll: 'Clear All',
    noActiveAlarms: 'No active alarms',
    viewHistory: 'View History',

    // Settings
    preferences: 'Preferences and security',
    language: 'Language',
    selectLanguage: 'Select your preferred interface language.',
    security: 'Security',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    updatePassword: 'Update Password',
    forgotAccessTitle: 'Forgot Access?',
    forgotAccessDescription: 'For security reasons, access recovery is managed by your system administrator. Please contact our technical support team to reset your credentials.',
    contactSupport: 'Contact Support',
    close: 'Close',
    passwordChangedSuccess: 'Password updated successfully!',
    passwordChangeError: 'Error updating password. Please try again.',
    confirmPassword: 'Confirm New Password',

    // Corporate Pages
    aboutPlatform: 'About Platform',
    productInfo: 'Product Information',
    appName: 'Application Name',
    appDescription: 'Short Description',
    appDescriptionText: 'Industrial IoT Platform for Real-time Monitoring & Remote Control of Refrigeration Systems.',
    versionBuild: 'Version / Build',
    releaseDate: 'Release Date',
    techSpecs: 'Technical Specifications',
    specMqtt: 'MQTT Protocol',
    specSecurity: 'Security',
    specCapacity: 'Capacity',
    specArchitecture: 'Architecture',
    specDatabase: 'Database',
    specHosting: 'Hosting',
    companyInfo: 'Company Information',
    addressInfo: 'Afric Froid HQ',
    allRightsReserved: '© 2026 Afric Froid. All rights reserved.',
    devCredits: 'Development Credits',
    architectureLead: 'Architecture & Lead Development',
    inPartnershipWith: 'In Partnership With',
    poweredBy: 'Powered By',
    alarmSound: 'Alarm Sound',
    enableAlarmSound: 'Audio alert enabled',
    disableAlarmSound: 'Audio alert disabled',
    testSound: 'Test Sound',
    brokerOnline: 'Broker Online',
    brokerConnecting: 'Connecting...',
    brokerError: 'Connection Error',
    brokerOffline: 'Offline Mode (Cached)',
    lastUpdate: 'Last update',
    ago: 'ago',
    seconds: 's',
    minutes: 'm',
    hours: 'h',
    alarmHistory: 'Alarm History',
    alarmAuditLog: 'Audit log of system anomalies and alerts',
    status: 'Status',
    alarm: 'Alarm',
    value: 'Value',
    threshold: 'Threshold',
    created: 'Created',
    details: 'Details',
    activeStatus: 'Active',
    acknowledgedStatus: 'Acknowledged',
    resolvedStatus: 'Resolved',
    lowSeverity: 'Low',
    mediumSeverity: 'Medium',
    highSeverity: 'High',
    criticalSeverity: 'Critical',
    autoResolvedAt: 'Auto-resolved at',
    acknowledgedAtLabel: 'Acknowledged at',
    monitoringActive: 'Currently active and monitoring',
    confirmClearHistory: 'Are you sure you want to clear your alarm history?',
    limit: 'Limit',
    refresh: 'Refresh',
    clearHistory: 'Clear History',
    clearHistoryError: 'Could not clear alarm history',
    noHistoricalAlarmsToClear:
      'There are no resolved or acknowledged alarms to remove. Active alarms stay until the process returns to normal.',
    systemRunningSmoothly: 'Your system is running smoothly.',
    noAlarmHistory: 'No alarm history found.',
    vsLastHour: 'vs last hour',
    dashboardLoading: 'Loading Dashboard Architecture...',
    monitoringUnit: 'Monitoring Unit',
    plcliveFeed: 'Live Feed',
    noWidgets: 'No widgets configured for this dashboard yet.',
    awaitingData: 'Awaiting data...',
    sendCommand: 'SEND COMMAND',
    on: 'ON',
    off: 'OFF',
    publish: 'Publish',
    enterValue: 'Enter value...',
    option: 'Option',
    units: 'units',
    configuration: 'Configuration',
    live: 'Live',
    unsupportedWidget: 'Unsupported Widget',
    chartDataFromDatabase: 'History from database',
    chartSavedEverySeconds: 'Stored every {seconds}s (admin setting)',
    chartRange1h: '1h',
    chartRange6h: '6h',
    chartRange12h: '12h',
    chartRange24h: '24h',
    adminDatabaseSampleInterval: 'Database sample interval (charts & telemetry)',
    adminTelemetrySamplingTitle: 'Telemetry sampling',
    adminTelemetrySamplingBody:
      'How often one numeric value is saved to the database for this widget. Longer intervals reduce database load. Line charts use these stored points.',
    adminDatabaseSampleSelectTitle: 'Seconds between database samples',
    adminSample10s: 'Every 10 seconds',
    adminSample30s: 'Every 30 seconds',
    adminSample1m: 'Every 1 minute',
    adminSample2m: 'Every 2 minutes',
    adminSample5m: 'Every 5 minutes',
    adminSample10m: 'Every 10 minutes',
    adminSample15m: 'Every 15 minutes',
    adminSample30m: 'Every 30 minutes',
    adminSample1h: 'Every 1 hour',
    adminChartTimeRangeNote:
      'Line chart time range (1h / 6h / 12h / 24h) is chosen on the client dashboard.',
    adminChartYMinOptional: 'Y axis min (optional)',
    adminChartYMaxOptional: 'Y axis max (optional)',
    adminChartYMinTitle: 'Fixed Y-axis minimum',
    adminChartYMaxTitle: 'Fixed Y-axis maximum',
    adminPlaceholderAuto: 'auto',
    adminShowPoints: 'Show points',
    widgetConfigTopic: 'Topic',
    widgetConfigVariable: 'Variable',
    widgetConfigAction: 'Action',
    adminWidgetConfiguration: 'Widget configuration',
    downloadWidgetData: 'Download data',
    downloadWidgetDataTooltip:
      'Download all stored readings for this widget as a CSV file (up to {days} days of history).',
    exportTelemetryEmpty: 'No stored readings to export for this widget yet.',
    exportTelemetryError: 'Could not download telemetry. Please try again.',
    exportTelemetryDownloading: 'Downloading…',
    exportTelemetryDownloaded: 'Downloaded',
    exportCsvTimestamp: 'timestamp_utc',
    exportCsvValue: 'value',
    exportCsvVariable: 'variable',
    exportCsvUnit: 'unit',
  },
  fr: {
    // Navigation & Sessions
    dashboard: 'Tableau de bord',
    controls: 'Commandes',
    settings: 'Paramètres',
    users: 'Gestion des utilisateurs',
    logout: 'Déconnexion',
    about: 'À propos',
    terms: 'Conditions d\'utilisation',
    privacy: 'Politique de confidentialité',
    welcome: 'Bon retour',

    // Login Page
    clientPortal: 'Portail Client',
    industrialMonitoring: 'Accès sécurisé à votre tableau de bord de surveillance industrielle.',
    companyId: 'ID Entreprise',
    password: 'Mot de passe sécurisé',
    rememberDevice: 'Se souvenir de l\'appareil',
    forgotAccess: 'Accès oublié ?',
    accessDashboard: 'Accéder au tableau de bord',
    visitWebsite: 'Visiter le site officiel',
    systemOperational: 'Système Opérationnel',
    tagline: 'Le spécialiste du froid industriel et commercial. Nous vous accompagnons de l\'étude à la réalisation.',

    // Dashboard & Controls
    systemStatus: 'État du système',
    temperature: 'Température',
    pressure: 'Pression',
    setpoint: 'Consigne',
    active: 'Actif',
    inactive: 'Inactif',
    save: 'Enregistrer',
    cancel: 'Annuler',
    alarms: 'Alarmes',
    acknowledge: 'Acquitter',
    clearAll: 'Tout effacer',
    noActiveAlarms: 'Aucune alarme active',
    viewHistory: 'Voir l\'historique',

    // Settings
    preferences: 'Préférences et sécurité',
    language: 'Langue',
    selectLanguage: 'Sélectionnez votre langue d\'interface préférée.',
    security: 'Sécurité',
    currentPassword: 'Mot de passe actuel',
    newPassword: 'Nouveau mot de passe',
    updatePassword: 'Modifier le mot de passe',
    forgotAccessTitle: 'Accès Oublié ?',
    forgotAccessDescription: 'Pour des raisons de sécurité, la récupération d\'accès est gérée par votre administrateur système. Veuillez contacter notre équipe de support technique pour réinitialiser vos identifiants.',
    contactSupport: 'Contacter le Support',
    close: 'Fermer',
    passwordChangedSuccess: 'Mot de passe mis à jour avec succès !',
    passwordChangeError: 'Erreur lors de la mise à jour du mot de passe. Veuillez réessayer.',
    confirmPassword: 'Confirmer le nouveau mot de passe',

    // Corporate Pages
    aboutPlatform: 'À propos de la plateforme',
    productInfo: 'Informations sur le produit',
    appName: 'Nom de l\'application',
    appDescription: 'Brève description',
    appDescriptionText: 'Plateforme IoT industrielle pour la surveillance en temps réel et le contrôle à distance des systèmes de réfrigération.',
    versionBuild: 'Version / Build',
    releaseDate: 'Date de sortie',
    techSpecs: 'Spécifications Techniques',
    specMqtt: 'Protocole MQTT',
    specSecurity: 'Sécurité',
    specCapacity: 'Capacité',
    specArchitecture: 'Architecture',
    specDatabase: 'Base de données',
    specHosting: 'Hébergement',
    companyInfo: 'Informations sur l\'entreprise',
    addressInfo: 'Siège Afric Froid',
    allRightsReserved: '© 2026 Afric Froid. Tous droits réservés.',
    devCredits: 'Crédits de Développement',
    architectureLead: 'Architecture et Développement Principal',
    inPartnershipWith: 'En Partenariat Avec',
    poweredBy: 'Propulsé Par',
    alarmSound: 'Alarmes Sonores',
    enableAlarmSound: 'Alerte sonore activée',
    disableAlarmSound: 'Alerte sonore désactivée',
    testSound: 'Tester le son',
    brokerOnline: 'Broker en ligne',
    brokerConnecting: 'Connexion...',
    brokerError: 'Erreur connexion',
    brokerOffline: 'Mode Hors-ligne (Caché)',
    lastUpdate: 'Dernière m-à-j',
    ago: 'il y a',
    seconds: 's',
    minutes: 'm',
    hours: 'h',
    alarmHistory: 'Historique des Alarmes',
    alarmAuditLog: 'Journal d’audit des anomalies et alertes du système',
    status: 'État',
    alarm: 'Alarme',
    value: 'Valeur',
    threshold: 'Seuil',
    created: 'Créée',
    details: 'Détails',
    activeStatus: 'Actif',
    acknowledgedStatus: 'Acquitté',
    resolvedStatus: 'Résolu',
    lowSeverity: 'Faible',
    mediumSeverity: 'Moyenne',
    highSeverity: 'Haute',
    criticalSeverity: 'Critique',
    autoResolvedAt: 'Auto-résolu à',
    acknowledgedAtLabel: 'Acquitté à',
    monitoringActive: 'Actuellement actif et en surveillance',
    confirmClearHistory: 'Êtes-vous sûr de vouloir effacer votre historique d’alarmes ?',
    limit: 'Limite',
    refresh: 'Actualiser',
    clearHistory: 'Effacer l’Historique',
    clearHistoryError: 'Impossible d’effacer l’historique des alarmes',
    noHistoricalAlarmsToClear:
      'Aucune alarme résolue ou acquittée à supprimer. Les alarmes actives restent jusqu’à retour à la normale du procédé.',
    systemRunningSmoothly: 'Votre système fonctionne correctement.',
    noAlarmHistory: 'Aucun historique d’alarme trouvé.',
    vsLastHour: 'vs heure précédente',
    dashboardLoading: 'Chargement de l\'architecture du tableau de bord...',
    monitoringUnit: 'Unité de surveillance',
    plcliveFeed: 'Flux en direct',
    noWidgets: 'Aucun widget configuré pour ce tableau de bord.',
    awaitingData: 'En attente de données...',
    sendCommand: 'ENVOYER COMMANDE',
    on: 'MARCHE',
    off: 'ARRÊT',
    publish: 'Publier',
    enterValue: 'Entrez la valeur...',
    option: 'Option',
    units: 'unités',
    configuration: 'Configuration',
    live: 'Direct',
    unsupportedWidget: 'Widget non supporté',
    chartDataFromDatabase: 'Historique depuis la base',
    chartSavedEverySeconds: 'Enregistré toutes les {seconds}s (réglage admin)',
    chartRange1h: '1 h',
    chartRange6h: '6 h',
    chartRange12h: '12 h',
    chartRange24h: '24 h',
    adminDatabaseSampleInterval: 'Intervalle d’échantillonnage en base (graphiques et télémétrie)',
    adminTelemetrySamplingTitle: 'Échantillonnage télémétrique',
    adminTelemetrySamplingBody:
      'Fréquence d’enregistrement d’une valeur numérique en base pour ce widget. Un intervalle plus long réduit la charge sur la base. Les graphiques utilisent ces points.',
    adminDatabaseSampleSelectTitle: 'Secondes entre chaque enregistrement en base',
    adminSample10s: 'Toutes les 10 secondes',
    adminSample30s: 'Toutes les 30 secondes',
    adminSample1m: 'Chaque minute',
    adminSample2m: 'Toutes les 2 minutes',
    adminSample5m: 'Toutes les 5 minutes',
    adminSample10m: 'Toutes les 10 minutes',
    adminSample15m: 'Toutes les 15 minutes',
    adminSample30m: 'Toutes les 30 minutes',
    adminSample1h: 'Chaque heure',
    adminChartTimeRangeNote:
      'La plage temporelle du graphique (1 h / 6 h / 12 h / 24 h) est choisie sur le tableau de bord client.',
    adminChartYMinOptional: 'Axe Y min (optionnel)',
    adminChartYMaxOptional: 'Axe Y max (optionnel)',
    adminChartYMinTitle: 'Minimum fixe de l’axe Y',
    adminChartYMaxTitle: 'Maximum fixe de l’axe Y',
    adminPlaceholderAuto: 'auto',
    adminShowPoints: 'Afficher les points',
    widgetConfigTopic: 'Topic',
    widgetConfigVariable: 'Variable',
    widgetConfigAction: 'Action',
    adminWidgetConfiguration: 'Configuration du widget',
    downloadWidgetData: 'Télécharger les données',
    downloadWidgetDataTooltip:
      'Télécharger toutes les mesures enregistrées pour ce widget au format CSV (jusqu’à {days} jours d’historique).',
    exportTelemetryEmpty: 'Aucune mesure enregistrée à exporter pour ce widget pour le moment.',
    exportTelemetryError: 'Impossible de télécharger les données. Veuillez réessayer.',
    exportTelemetryDownloading: 'Téléchargement…',
    exportTelemetryDownloaded: 'Téléchargé',
    exportCsvTimestamp: 'horodatage_utc',
    exportCsvValue: 'valeur',
    exportCsvVariable: 'variable',
    exportCsvUnit: 'unite',
  }
};
